import React, { useState } from 'react';
import { useWorkflow } from '../hooks/useWorkflow';
import { StatusBadge } from '../components/StatusBadge';
import { 
  TrendingUp, Download, Calendar, Filter, FileSpreadsheet, 
  FileText, CheckCircle2, AlertCircle, RefreshCw, BarChart3, 
  PieChart, Activity, DollarSign, ArrowUpRight, BookOpen
} from 'lucide-react';
import { Document } from '../types';

export const ReportsPage: React.FC = () => {
  const { documents, user } = useWorkflow();

  // Filters state
  const [docType, setDocType] = useState<string>('ALL');
  const [sectionFilter, setSectionFilter] = useState<string>('ALL');
  const [minAmount, setMinAmount] = useState<string>('');
  const [maxAmount, setMaxAmount] = useState<string>('');
  const [searchTerm, setSearchTerm] = useState<string>('');

  // Export progress simulation state
  const [exportingType, setExportingType] = useState<'PDF' | 'CSV' | null>(null);
  const [exportProgress, setExportProgress] = useState<number>(0);
  const [exportStatusText, setExportStatusText] = useState<string>('');

  // Filter documents
  const filteredDocs = documents.filter(doc => {
    const matchesSearch = doc.id.toLowerCase().includes(searchTerm.toLowerCase()) || 
                          doc.title.toLowerCase().includes(searchTerm.toLowerCase()) ||
                          doc.supplier.toLowerCase().includes(searchTerm.toLowerCase());
    
    const matchesType = docType === 'ALL' || doc.type === docType;
    const matchesSection = sectionFilter === 'ALL' || doc.currentSection === sectionFilter;
    
    const amt = doc.amount;
    const matchesMin = minAmount === '' || amt >= parseFloat(minAmount);
    const matchesMax = maxAmount === '' || amt <= parseFloat(maxAmount);

    return matchesSearch && matchesType && matchesSection && matchesMin && matchesMax;
  });

  // Calculate totals
  const totalAmount = filteredDocs.reduce((acc, d) => acc + d.amount, 0);
  const totalCount = filteredDocs.length;
  
  const totalPaid = filteredDocs
    .filter(d => d.status === 'CASHIER_PAID')
    .reduce((acc, d) => acc + d.amount, 0);

  const totalPending = filteredDocs
    .filter(d => d.status !== 'CASHIER_PAID')
    .reduce((acc, d) => acc + d.amount, 0);

  const returnedDocsCount = filteredDocs.filter(d => d.status === 'ACCOUNTING_RETURNED').length;

  // Group by document types
  const typesData = {
    PR: filteredDocs.filter(d => d.type === 'PR').reduce((acc, d) => acc + d.amount, 0),
    DV: filteredDocs.filter(d => d.type === 'DV').reduce((acc, d) => acc + d.amount, 0),
    PO: filteredDocs.filter(d => d.type === 'PO').reduce((acc, d) => acc + d.amount, 0),
  };

  const typesCounts = {
    PR: filteredDocs.filter(d => d.type === 'PR').length,
    DV: filteredDocs.filter(d => d.type === 'DV').length,
    PO: filteredDocs.filter(d => d.type === 'PO').length,
  };

  // Group by workflow section
  const sectionsCount = {
    BUDGET: filteredDocs.filter(d => d.currentSection === 'BUDGET').length,
    ACCOUNTING: filteredDocs.filter(d => d.currentSection === 'ACCOUNTING').length,
    CASHIER: filteredDocs.filter(d => d.currentSection === 'CASHIER').length,
    COMPLETED: filteredDocs.filter(d => d.currentSection === 'COMPLETED').length,
  };

  const maxTypeAmount = Math.max(typesData.PR, typesData.DV, typesData.PO, 1);
  const maxSectionCount = Math.max(sectionsCount.BUDGET, sectionsCount.ACCOUNTING, sectionsCount.CASHIER, sectionsCount.COMPLETED, 1);

  // Trigger export simulation
  const handleExport = (type: 'PDF' | 'CSV') => {
    if (exportingType) return;
    setExportingType(type);
    setExportProgress(0);
    
    const steps = [
      'Compiling ledger elements...',
      'Validating clearances and metadata...',
      'Calculating obligation totals...',
      type === 'PDF' ? 'Signing document certificate...' : 'Generating spreadsheet schema...',
      'Finalizing secure export file...'
    ];

    let currentStep = 0;
    setExportStatusText(steps[currentStep]);

    const interval = setInterval(() => {
      setExportProgress(prev => {
        const next = prev + 10;
        if (next % 20 === 0 && currentStep < steps.length - 1) {
          currentStep++;
          setExportStatusText(steps[currentStep]);
        }
        if (next >= 100) {
          clearInterval(interval);
          setTimeout(() => {
            setExportingType(null);
            setExportProgress(0);
            
            // Create a fake download link for demonstration
            const blob = new Blob(
              [type === 'CSV' 
                ? `ID,Title,Type,Supplier,Amount,Section,Status\n` + filteredDocs.map(d => `"${d.id}","${d.title}","${d.type}","${d.supplier}",${d.amount},"${d.currentSection}","${d.status}"`).join('\n')
                : `DOST REGION V FINTRA SUMMARY REPORT\nGenerated by: ${user?.name}\nTotal Count: ${totalCount}\nTotal Amount: ₱${totalAmount}`
              ], 
              { type: type === 'CSV' ? 'text/csv' : 'text/plain' }
            );
            const url = URL.createObjectURL(blob);
            const a = document.createElement('a');
            a.href = url;
            a.download = `DOST-FinTra-Report-${new Date().toISOString().split('T')[0]}.${type === 'CSV' ? 'csv' : 'txt'}`;
            document.body.appendChild(a);
            a.click();
            document.body.removeChild(a);
            URL.revokeObjectURL(url);
          }, 600);
          return 100;
        }
        return next;
      });
    }, 200);
  };

  return (
    <div className="space-y-6 font-inter animate-fade-in">
      
      {/* Upper header action banner */}
      <div className="bg-white border border-slate-200 p-6 rounded-2xl flex flex-col md:flex-row items-start md:items-center justify-between gap-4 shadow-xs">
        <div>
          <h1 className="text-2xl font-black text-slate-900 tracking-tight font-sans">
            Finance Intelligence & Reports
          </h1>
          <p className="text-xs text-slate-500 mt-1">
            Analyze fund allocations, section bottleneck indicators, and export authenticated government ledgers.
          </p>
        </div>
        
        {/* Rapid Actions */}
        <div className="flex flex-wrap gap-2 shrink-0">
          <button
            onClick={() => handleExport('CSV')}
            disabled={exportingType !== null}
            className="flex items-center gap-1.5 px-3 py-2 bg-emerald-50 text-emerald-700 hover:bg-emerald-100 border border-emerald-200 text-xs font-bold rounded-lg transition cursor-pointer select-none disabled:opacity-50"
          >
            <FileSpreadsheet className="w-4 h-4 text-emerald-600" />
            <span>Export CSV</span>
          </button>
          <button
            onClick={() => handleExport('PDF')}
            disabled={exportingType !== null}
            className="flex items-center gap-1.5 px-3 py-2 bg-red-50 text-red-700 hover:bg-red-100 border border-red-200 text-xs font-bold rounded-lg transition cursor-pointer select-none disabled:opacity-50"
          >
            <FileText className="w-4 h-4 text-red-600" />
            <span>Export summary</span>
          </button>
        </div>
      </div>

      {/* Export progress panel overlay if exporting */}
      {exportingType && (
        <div className="bg-[#0f172a] text-white p-5 rounded-xl border border-slate-750 flex flex-col md:flex-row items-center justify-between gap-4 animate-pulse">
          <div className="flex items-center gap-3 w-full md:w-auto">
            <div className="p-2.5 bg-white/10 rounded-lg text-blue-400">
              <RefreshCw className="w-5 h-5 animate-spin" />
            </div>
            <div>
              <p className="text-xs font-bold text-slate-100">Simulating Secure {exportingType} Ledger Export</p>
              <p className="text-[10px] text-slate-400 font-mono mt-0.5">{exportStatusText}</p>
            </div>
          </div>
          <div className="w-full md:w-64">
            <div className="flex justify-between text-[10px] text-slate-400 font-mono mb-1 font-bold">
              <span>PROGRESS</span>
              <span>{exportProgress}%</span>
            </div>
            <div className="w-full bg-slate-800 rounded-full h-1.5 overflow-hidden">
              <div 
                className="bg-blue-500 h-1.5 rounded-full transition-all duration-150" 
                style={{ width: `${exportProgress}%` }}
              ></div>
            </div>
          </div>
        </div>
      )}

      {/* Filter Matrix Workspace */}
      <div className="bg-white border border-slate-200 rounded-2xl p-5 shadow-2xs">
        <div className="flex items-center gap-2 mb-4">
          <Filter className="w-4 h-4 text-slate-600" />
          <h2 className="text-xs uppercase font-extrabold tracking-wider text-slate-600">
            Interactive Filter Workspace
          </h2>
        </div>
        
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-5 gap-3.5">
          {/* Search Term */}
          <div className="space-y-1">
            <label className="text-[10px] font-bold text-slate-500 uppercase">Search Details</label>
            <input 
              type="text" 
              placeholder="ID, Title, or Supplier..."
              value={searchTerm}
              onChange={(e) => setSearchTerm(e.target.value)}
              className="w-full bg-slate-50 hover:bg-slate-100 focus:bg-white text-xs border border-slate-250 rounded-lg px-3 py-2 text-slate-800 placeholder-slate-400 focus:outline-none focus:ring-1 focus:ring-[#025191] transition"
            />
          </div>

          {/* Type Filter */}
          <div className="space-y-1">
            <label className="text-[10px] font-bold text-slate-500 uppercase">Document Type</label>
            <select
              value={docType}
              onChange={(e) => setDocType(e.target.value)}
              className="w-full bg-slate-50 border border-slate-250 rounded-lg px-3 py-2 text-xs font-semibold text-slate-700 focus:ring-1 focus:ring-[#025191] focus:outline-none"
            >
              <option value="ALL">All Types (PR, DV, PO)</option>
              <option value="PR">PR (Purchase Request)</option>
              <option value="DV">DV (Disbursement Voucher)</option>
              <option value="PO">PO (Purchase Order)</option>
            </select>
          </div>

          {/* Section Filter */}
          <div className="space-y-1">
            <label className="text-[10px] font-bold text-slate-500 uppercase">Active Section Location</label>
            <select
              value={sectionFilter}
              onChange={(e) => setSectionFilter(e.target.value)}
              className="w-full bg-slate-50 border border-slate-250 rounded-lg px-3 py-2 text-xs font-semibold text-slate-700 focus:ring-1 focus:ring-[#025191] focus:outline-none"
            >
              <option value="ALL">All Locations</option>
              <option value="BUDGET">Budget Section</option>
              <option value="ACCOUNTING">Accounting Section</option>
              <option value="CASHIER">Cashier Section</option>
              <option value="COMPLETED">Completed ledger</option>
            </select>
          </div>

          {/* Min Amount */}
          <div className="space-y-1">
            <label className="text-[10px] font-bold text-slate-500 uppercase">Min Value (₱)</label>
            <input 
              type="number" 
              placeholder="Min amount"
              value={minAmount}
              onChange={(e) => setMinAmount(e.target.value)}
              className="w-full bg-slate-50 text-xs border border-slate-250 rounded-lg px-3 py-2 text-slate-800 placeholder-slate-400 focus:outline-none focus:ring-1 focus:ring-[#025191]"
            />
          </div>

          {/* Max Amount */}
          <div className="space-y-1">
            <label className="text-[10px] font-bold text-slate-500 uppercase">Max Value (₱)</label>
            <input 
              type="number" 
              placeholder="Max amount"
              value={maxAmount}
              onChange={(e) => setMaxAmount(e.target.value)}
              className="w-full bg-slate-50 text-xs border border-slate-250 rounded-lg px-3 py-2 text-slate-800 placeholder-slate-400 focus:outline-none focus:ring-1 focus:ring-[#025191]"
            />
          </div>
        </div>

        {/* Reset filters action */}
        {(docType !== 'ALL' || sectionFilter !== 'ALL' || minAmount !== '' || maxAmount !== '' || searchTerm !== '') && (
          <div className="mt-4 pt-3.5 border-t border-slate-100 flex justify-end">
            <button
              onClick={() => {
                setDocType('ALL');
                setSectionFilter('ALL');
                setMinAmount('');
                setMaxAmount('');
                setSearchTerm('');
              }}
              className="text-[10px] font-black uppercase text-red-500 hover:text-red-700 flex items-center gap-1 cursor-pointer select-none"
            >
              Clear Workspace Filters ({filteredDocs.length} matching)
            </button>
          </div>
        )}
      </div>

      {/* KPI Highlight Matrix */}
      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
        {/* Total Aggregate Allocations */}
        <div className="bg-white border border-slate-200 p-5 rounded-2xl shadow-xs relative overflow-hidden">
          <div className="absolute right-0 top-0 h-full w-1 bg-blue-500"></div>
          <div className="flex justify-between items-start">
            <div>
              <p className="text-[9px] uppercase tracking-wider font-extrabold text-slate-400">Total Filtered Funds</p>
              <h3 className="text-xl font-black text-slate-800 tracking-tight mt-1">
                ₱{totalAmount.toLocaleString()}
              </h3>
              <p className="text-[10px] text-slate-500 mt-1 font-mono">{totalCount} transaction documents</p>
            </div>
            <div className="p-2.5 bg-blue-50 text-blue-600 rounded-xl">
              <DollarSign className="w-5 h-5" />
            </div>
          </div>
        </div>

        {/* Paid / Released Allocations */}
        <div className="bg-white border border-slate-200 p-5 rounded-2xl shadow-xs relative overflow-hidden">
          <div className="absolute right-0 top-0 h-full w-1 bg-emerald-500"></div>
          <div className="flex justify-between items-start">
            <div>
              <p className="text-[9px] uppercase tracking-wider font-extrabold text-slate-400">Disbursed Ledger</p>
              <h3 className="text-xl font-black text-slate-800 tracking-tight mt-1">
                ₱{totalPaid.toLocaleString()}
              </h3>
              <p className="text-[10px] text-emerald-600 mt-1 font-semibold flex items-center gap-0.5">
                <ArrowUpRight className="w-3 h-3" />
                {totalCount > 0 ? Math.round((totalPaid / (totalAmount || 1)) * 100) : 0}% of filtered total
              </p>
            </div>
            <div className="p-2.5 bg-emerald-50 text-emerald-600 rounded-xl">
              <CheckCircle2 className="w-5 h-5" />
            </div>
          </div>
        </div>

        {/* Pending pipeline funds */}
        <div className="bg-white border border-slate-200 p-5 rounded-2xl shadow-xs relative overflow-hidden">
          <div className="absolute right-0 top-0 h-full w-1 bg-amber-500"></div>
          <div className="flex justify-between items-start">
            <div>
              <p className="text-[9px] uppercase tracking-wider font-extrabold text-slate-400">Active Pipeline Funds</p>
              <h3 className="text-xl font-black text-slate-800 tracking-tight mt-1">
                ₱{totalPending.toLocaleString()}
              </h3>
              <p className="text-[10px] text-amber-600 mt-1 font-semibold">
                Under operational clearances
              </p>
            </div>
            <div className="p-2.5 bg-amber-50 text-amber-650 rounded-xl">
              <Activity className="w-5 h-5" />
            </div>
          </div>
        </div>

        {/* Returned count */}
        <div className="bg-white border border-slate-200 p-5 rounded-2xl shadow-xs relative overflow-hidden">
          <div className="absolute right-0 top-0 h-full w-1 bg-red-500"></div>
          <div className="flex justify-between items-start">
            <div>
              <p className="text-[9px] uppercase tracking-wider font-extrabold text-slate-400">Compliance Bottlenecks</p>
              <h3 className="text-xl font-black text-slate-800 tracking-tight mt-1">
                {returnedDocsCount} Documents
              </h3>
              <p className="text-[10px] text-red-500 mt-1 font-semibold">
                Returned for modifications
              </p>
            </div>
            <div className="p-2.5 bg-red-50 text-red-600 rounded-xl">
              <AlertCircle className="w-5 h-5" />
            </div>
          </div>
        </div>
      </div>

      {/* Modern custom SVG visual analytics charts */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        
        {/* Chart A: Amount Allocation by Document Type */}
        <div className="bg-white border border-slate-200 p-6 rounded-2xl shadow-xs">
          <div className="flex items-center justify-between mb-6">
            <div className="flex items-center gap-2">
              <BarChart3 className="w-4 h-4 text-[#025191]" />
              <h3 className="text-sm font-extrabold text-slate-800 uppercase tracking-wide">
                Amount Distribution by Type
              </h3>
            </div>
            <span className="text-[9px] font-mono text-slate-400">VALUES IN PESO (₱)</span>
          </div>

          <div className="space-y-5">
            {/* PR Type */}
            <div className="space-y-1.5">
              <div className="flex items-center justify-between text-xs">
                <span className="font-bold text-slate-700">PR (Purchase Request)</span>
                <span className="font-mono text-slate-500">₱{typesData.PR.toLocaleString()} ({typesCounts.PR} docs)</span>
              </div>
              <div className="w-full bg-slate-100 rounded-lg h-3 overflow-hidden">
                <div 
                  className="bg-[#025191] h-3 rounded-lg transition-all duration-500"
                  style={{ width: `${(typesData.PR / maxTypeAmount) * 100}%` }}
                ></div>
              </div>
            </div>

            {/* DV Type */}
            <div className="space-y-1.5">
              <div className="flex items-center justify-between text-xs">
                <span className="font-bold text-slate-700">DV (Disbursement Voucher)</span>
                <span className="font-mono text-slate-500">₱{typesData.DV.toLocaleString()} ({typesCounts.DV} docs)</span>
              </div>
              <div className="w-full bg-slate-100 rounded-lg h-3 overflow-hidden">
                <div 
                  className="bg-[#013c6e] h-3 rounded-lg transition-all duration-500"
                  style={{ width: `${(typesData.DV / maxTypeAmount) * 100}%` }}
                ></div>
              </div>
            </div>

            {/* PO Type */}
            <div className="space-y-1.5">
              <div className="flex items-center justify-between text-xs">
                <span className="font-bold text-slate-700">PO (Purchase Order)</span>
                <span className="font-mono text-slate-500">₱{typesData.PO.toLocaleString()} ({typesCounts.PO} docs)</span>
              </div>
              <div className="w-full bg-slate-100 rounded-lg h-3 overflow-hidden">
                <div 
                  className="bg-[#22c55e] h-3 rounded-lg transition-all duration-500"
                  style={{ width: `${(typesData.PO / maxTypeAmount) * 100}%` }}
                ></div>
              </div>
            </div>
          </div>

          <div className="mt-6 pt-4 border-t border-slate-100 text-[10px] text-slate-400 flex items-center justify-between">
            <span>Totals based on your active filtered selection</span>
            <span className="font-bold text-[#025191]">TOTAL: ₱{totalAmount.toLocaleString()}</span>
          </div>
        </div>

        {/* Chart B: Section Queue Load Funnel */}
        <div className="bg-white border border-slate-200 p-6 rounded-2xl shadow-xs">
          <div className="flex items-center justify-between mb-6">
            <div className="flex items-center gap-2">
              <Activity className="w-4 h-4 text-emerald-600" />
              <h3 className="text-sm font-extrabold text-slate-800 uppercase tracking-wide">
                Clearance Queue Bottlenecks
              </h3>
            </div>
            <span className="text-[9px] font-mono text-slate-400">DOCUMENT COUNTS</span>
          </div>

          <div className="space-y-4">
            {/* Budget */}
            <div className="flex items-center gap-4 text-xs">
              <div className="w-28 font-bold text-slate-600 truncate">Budget Desk</div>
              <div className="flex-1 flex items-center gap-2">
                <div className="flex-1 bg-slate-100 h-2.5 rounded-lg overflow-hidden">
                  <div 
                    className="bg-sky-500 h-2.5 rounded-lg transition-all duration-500" 
                    style={{ width: `${(sectionsCount.BUDGET / maxSectionCount) * 100}%` }}
                  ></div>
                </div>
                <span className="font-mono font-bold w-6 text-right">{sectionsCount.BUDGET}</span>
              </div>
            </div>

            {/* Accounting */}
            <div className="flex items-center gap-4 text-xs">
              <div className="w-28 font-bold text-slate-600 truncate">Accounting Desk</div>
              <div className="flex-1 flex items-center gap-2">
                <div className="flex-1 bg-slate-100 h-2.5 rounded-lg overflow-hidden">
                  <div 
                    className="bg-amber-500 h-2.5 rounded-lg transition-all duration-500" 
                    style={{ width: `${(sectionsCount.ACCOUNTING / maxSectionCount) * 100}%` }}
                  ></div>
                </div>
                <span className="font-mono font-bold w-6 text-right">{sectionsCount.ACCOUNTING}</span>
              </div>
            </div>

            {/* Cashier */}
            <div className="flex items-center gap-4 text-xs">
              <div className="w-28 font-bold text-slate-600 truncate">Cashier Desk</div>
              <div className="flex-1 flex items-center gap-2">
                <div className="flex-1 bg-slate-100 h-2.5 rounded-lg overflow-hidden">
                  <div 
                    className="bg-blue-600 h-2.5 rounded-lg transition-all duration-500" 
                    style={{ width: `${(sectionsCount.CASHIER / maxSectionCount) * 100}%` }}
                  ></div>
                </div>
                <span className="font-mono font-bold w-6 text-right">{sectionsCount.CASHIER}</span>
              </div>
            </div>

            {/* Completed */}
            <div className="flex items-center gap-4 text-xs">
              <div className="w-28 font-bold text-slate-600 truncate">Paid / Completed</div>
              <div className="flex-1 flex items-center gap-2">
                <div className="flex-1 bg-slate-100 h-2.5 rounded-lg overflow-hidden">
                  <div 
                    className="bg-emerald-500 h-2.5 rounded-lg transition-all duration-500" 
                    style={{ width: `${(sectionsCount.COMPLETED / maxSectionCount) * 100}%` }}
                  ></div>
                </div>
                <span className="font-mono font-bold w-6 text-right">{sectionsCount.COMPLETED}</span>
              </div>
            </div>
          </div>

          <div className="mt-8 pt-4 border-t border-slate-100 text-[10px] text-slate-400 flex items-center justify-between">
            <span>High values indicate administrative backlogs</span>
            <span className="text-emerald-600 font-bold">TOTAL DOCS: {totalCount}</span>
          </div>
        </div>

      </div>

      {/* Filtered Records Data Table */}
      <div className="bg-white border border-slate-200 rounded-2xl overflow-hidden shadow-xs">
        <div className="p-5 border-b border-slate-100 flex items-center justify-between bg-slate-50">
          <div>
            <h3 className="text-sm font-black text-slate-800 tracking-tight">Active Report Ledger</h3>
            <p className="text-[10px] text-slate-500 mt-0.5">Showing {filteredDocs.length} of {documents.length} transaction entries</p>
          </div>
          <span className="px-2.5 py-1 text-[9px] font-black uppercase text-slate-600 border border-slate-200 bg-white rounded-lg">
            Region V Secure Database
          </span>
        </div>

        <div className="overflow-x-auto">
          <table className="w-full text-left border-collapse text-xs">
            <thead>
              <tr className="border-b border-slate-200 bg-slate-100/50 text-slate-600 select-none font-bold">
                <th className="px-5 py-3">Document Reference</th>
                <th className="px-5 py-3">Title & Creditor</th>
                <th className="px-5 py-3">Section Location</th>
                <th className="px-5 py-3">Obligated Value</th>
                <th className="px-5 py-3">Check / ORS / DV Numbers</th>
                <th className="px-5 py-3">Compliance Status</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-slate-100">
              {filteredDocs.length > 0 ? (
                filteredDocs.map((doc) => (
                  <tr key={doc.id} className="hover:bg-slate-50/80 transition duration-150">
                    <td className="px-5 py-3.5 whitespace-nowrap font-mono font-bold text-[#025191]">
                      {doc.id}
                      <span className="ml-1.5 px-1.5 py-0.5 text-[9px] font-sans font-black bg-slate-100 text-slate-600 rounded">
                        {doc.type}
                      </span>
                    </td>
                    <td className="px-5 py-3.5">
                      <div className="font-bold text-slate-800 truncate max-w-xs">{doc.title}</div>
                      <div className="text-[10px] text-slate-400 mt-0.5 font-medium truncate max-w-xs">Payee: {doc.supplier}</div>
                    </td>
                    <td className="px-5 py-3.5 whitespace-nowrap">
                      <span className="font-semibold text-slate-600 uppercase tracking-wider text-[10px] bg-slate-100 px-2 py-1 rounded">
                        {doc.currentSection === 'COMPLETED' ? '🏆 Completed' : `📍 ${doc.currentSection}`}
                      </span>
                    </td>
                    <td className="px-5 py-3.5 whitespace-nowrap font-mono font-bold text-slate-800">
                      ₱{doc.amount.toLocaleString()}
                    </td>
                    <td className="px-5 py-3.5 whitespace-nowrap">
                      <div className="space-y-0.5 font-mono text-[10px]">
                        {doc.orsNumber && (
                          <div className="text-blue-600">
                            <span className="text-slate-400">ORS: </span>{doc.orsNumber}
                          </div>
                        )}
                        {doc.dvNumber && (
                          <div className="text-emerald-600">
                            <span className="text-slate-400">DV: </span>{doc.dvNumber}
                          </div>
                        )}
                        {doc.checkNumber && (
                          <div className="text-indigo-600">
                            <span className="text-slate-400">CHK: </span>{doc.checkNumber}
                          </div>
                        )}
                        {!doc.orsNumber && !doc.dvNumber && !doc.checkNumber && (
                          <span className="text-slate-400 italic">None registered yet</span>
                        )}
                      </div>
                    </td>
                    <td className="px-5 py-3.5 whitespace-nowrap">
                      <StatusBadge status={doc.status} />
                    </td>
                  </tr>
                ))
              ) : (
                <tr>
                  <td colSpan={6} className="text-center py-10 text-slate-400 font-medium">
                    No transactions match your report search criteria.
                  </td>
                </tr>
              )}
            </tbody>
          </table>
        </div>
      </div>

    </div>
  );
};
